enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
excluded-patches = ""
included-patches = "'Remove player controls background'"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[GooglePhotos]
build-mode = "both"
arch = "both"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"


# dont build on gh actions (https://github.com/j-hc/revanced-magisk-module/issues/554)
[Music-Extended]
app-name = "Music"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[YouTube-Extended]
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

# [Twitch]
# enabled = false
# apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"
# uptodown-dlurl = "https://twitch.en.uptodown.com/android"
# # archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"

# [Twitch]
# enabled = false
# # archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"

# [TikTok]
# enabled = false
# # archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
# included-patches = "'SIM spoof'"

# [Messenger]
# enabled = false
# apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
# arch = "arm64-v8a"

# [Spotify]
# enabled = false
# uptodown-dlurl = "https://spotify.en.uptodown.com/android"

# [IconPackStudio]
# enabled = false
# apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"

[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"